name: Add Daily Q&A

on:
  schedule:
    - cron: "30 3 * * *"   # runs daily at ~09:00 IST
  workflow_dispatch: {}

permissions:
  contents: write

env:
  BATCH_SIZE: "3"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Append new Q&As
        run: python3 .github/scripts/add_qna.py
        env:
          SOURCE_REPO: ${{ secrets.SOURCE_REPO }}
          SOURCE_BRANCH: ${{ secrets.SOURCE_BRANCH }}
          SOURCE_FILE: ${{ secrets.SOURCE_FILE }}
          SOURCE_TOKEN: ${{ secrets.SOURCE_TOKEN }}
          BATCH_SIZE: ${{ env.BATCH_SIZE }}
      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: add daily Q&As"
            git push
          else
            echo "Nothing to publish."
          fi
