name: Add Daily Q&A

on:
  schedule:
    - cron: "0 5 * * *"   # daily at 05:00 UTC (≈10:30 IST)
  workflow_dispatch: {}     # allow manual trigger

permissions:
  contents: write

env:
  SOURCE_REPO: ${{ secrets.SOURCE_REPO }}
  SOURCE_BRANCH: ${{ secrets.SOURCE_BRANCH }}
  SOURCE_FILE: ${{ secrets.SOURCE_FILE }}
  SOURCE_TOKEN: ${{ secrets.SOURCE_TOKEN }}
  BATCH_SIZE: "3"   # publish 3 Q&As per run (change to 2 if you like)

jobs:
  update-qna:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add new Q&As
        run: |
          python3 .github/scripts/add_qna.py

      - name: Commit changes (if any)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: add daily Q&As"
            git push
          else
            echo "No changes to commit."
          fi
